### ISSUE TITLE
Fetching Data "Error: Cannot read properties of undefined (reading 'program')"

### ISSUE THREAD

**Issue by ttytm** [silvestrevivo/solana-svelte-counter#21]
Hey, hello.

It's great to have work as yours as a reference. Working with new technologies with little documentation and examples I'm feeling deep appreciation for having people who provide like that.

Using your groundwork form your demo-app and the `svele-on-solana` packages I'm trying to deepen my knowledge. Where I'm running into some problems is trying to fetch data. 

How would you access the program variable to only fetch data?
```
let data
const getData = async () => {
  data = await $workSpace.program.account.baseAccount.all()

  // alternatively something like
  data = await $workSpace.program.account.baseAccount.fetch(
    $workSpace.baseAccount.publicKey
  );
  
  console.log(data);
  return data;
  };
```
Executing something like the example function above gives the error _`TypeError: Cannot read properties of undefined (reading 'program')`_

I know, this is an issue that isn't really related to the repo. It's more just me having difficulties to get ahead with something I don't quiet understand yet. Which is a rather egoistic thing to ask here. Anyway I'm opening this and hoping you can maybe provide an example inside the packages or demo app how fetch data outside the already provided RPC functions.

Sending love and blessings

Edit:
Trying for two more hours, and coming back more confused that the same code works in some situations when I'm connected to a wallet. But most of the time trying to fetch it's the Error: _`Uncaught (in promise) TypeError: can't access property "program", $workSpace is undefined`_. Possibly someone can tell what I am doing wrong.

**Comment by ttytm** [comment]
I've just seen you have other repos which will help me figures this out.

When I start working again and have some money I'll definitely want to make a donation for all of this.
Honor to you man. Love and blessings!

**Comment by silvestrevivo** [comment]
Hi @tobealive as you mentioned, this is not an issue related with the repo. I think the best place for your question is the Anchor Discord server. There you will find support for this and other questions related with it. Thanks!.
