### ISSUE TITLE
autoConnect is not working

### ISSUE THREAD

**Issue by silvestrevivo** [silvestrevivo/solana-svelte-counter#3]
AutoConnect is not working correctly. There are two possibilities: 

- 1. It is a UI issue
- 2. It is an issue coming from the adapter. 

My theory is that is an UI error of the current solution I made. Checking the code, it seems that we are clicking on `select()` and, since `autoConnect` is true, automatically the `connect()` function is triggered. That's why when `autoConnect` is false, the wallet is not popping up. 

I made a change locally and it is working. Even in the Vue implementation works like that. The `select()` function is to select the adapter, and the `connect()` is to popup the wallet selected. See here the Vue implementation: 

https://github.com/solana-labs/wallet-adapter/pull/118/files

The change I made was:

```
<script>
.... 

type WalletProvider = { id: number; text: string };

    let walletProviders: WalletProvider[] = [
        { id: 1, text: `Phantom` },
        { id: 2, text: `Slope` },
        { id: 3, text: `Solflare` }
    ];

    let selected;

    $: selected && selectWallet(selected.text);
</script>

<div class="wrapper-content">
		{#if $walletStore?.connected}
			<button on:click={() => $walletStore.disconnect()}>disconnect wallet</button>
		{:else}
			<p>Select wallet</p>
			<select bind:value={selected}>
				{#each walletProviders as walletProvider}
					<option value={walletProvider}>
						{walletProvider.text}
					</option>
				{/each}
			</select>
			{#if selected}
				<button on:click={() => $walletStore.connect()}>connect {selected.text}</button>
			{/if}
		{/if}
	</div>
```

**Comment by silvestrevivo** [comment]
select() and connect() has to be combined in the UI aligned to the VUE implementation.

**Comment by kylebuildsstuff** [comment]
Hello, I'm trying to implement these changes but am a bit lost. I'm not sure where to find `selectWallet` or where I'm supposed to add those changes. Would you happen to have a local branch we could look at?

The demo site looks like it works properly with autoConnect but when I follow the code example on master it doesn't connect automatically (requires 2 clicks).

**Comment by silvestrevivo** [comment]
@KTruong008 you are right. It seems that there has been a change in the Solana Packages that makes an impact in the behaviour of the autoConnect. This is something should be addressed. In the meantime, I recommend you to downgrade those packages to same version of this demo project. 

Thanks!!!!
